# Generated by Django 5.2.1 on 2025-05-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(verbose_name='Имя вида')),
                ('number', models.SmallIntegerField(verbose_name='Количество особей')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('anons', models.CharField(verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя')),
                ('age', models.SmallIntegerField(verbose_name='Возраст')),
                ('profession', models.CharField(verbose_name='Профессия')),
            ],
        ),
    ]
