# Generated by Django 5.2.1 on 2025-05-27 07:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reviews_alter_news_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Формат: +375 (29) XXX-XX-XX', regex='^\\+375 \\(29\\) \\d{3}-\\d{2}-\\d{2}$')])),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
    ]
