# Generated by Django 5.2.1 on 2025-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_staf_delete_staff_alter_animal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staf',
            name='animal',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
