# Generated by Django 5.2.1 on 2025-06-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_staf_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('sale', models.SmallIntegerField(verbose_name='%')),
                ('time', models.DateField(verbose_name='00.00.0000')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.AlterModelOptions(
            name='staf',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='animal.jpg'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/'),
        ),
        migrations.AddField(
            model_name='staf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='animal.jpg'),
        ),
    ]
