# Generated by Django 5.2.1 on 2025-06-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_image_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NativeCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name': 'Страна обитания',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='house',
            field=models.CharField(default='Вальер', verbose_name='Номер вальера'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, default='lions.jpg', upload_to='', verbose_name='animal.jpg'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='time',
            field=models.DateField(verbose_name='dd.mm.yyyy'),
        ),
    ]
