# Generated by Django 5.2.1 on 2025-06-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_nativecountry_animal_house_alter_animal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='mark',
            field=models.IntegerField(default=5, verbose_name='Оценка'),
        ),
    ]
