# Generated by Django 5.2.1 on 2025-06-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_reviews_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='QaA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quation', models.CharField()),
                ('answer', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('title', models.CharField()),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='reviews',
            name='mark',
            field=models.SmallIntegerField(default=5, verbose_name='Оценка'),
        ),
    ]
