# Generated by Django 5.2.1 on 2025-06-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_qaa_vacations_alter_reviews_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacations',
            new_name='Vacationss',
        ),
    ]
